[2024-12-04T04:40:01.133+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.sync_polygon_data scheduled__2024-12-04T01:00:00+00:00 [queued]>
[2024-12-04T04:40:01.167+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.sync_polygon_data scheduled__2024-12-04T01:00:00+00:00 [queued]>
[2024-12-04T04:40:01.168+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-04T04:40:01.169+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-12-04T04:40:01.169+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-04T04:40:01.202+0000] {taskinstance.py:1300} INFO - Executing <Task(AirbyteTriggerSyncOperator): sync_polygon_data> on 2024-12-04 01:00:00+00:00
[2024-12-04T04:40:01.209+0000] {standard_task_runner.py:55} INFO - Started process 2465 to run task
[2024-12-04T04:40:01.214+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'sync_polygon_data', 'scheduled__2024-12-04T01:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_BigQuery_sync.py', '--cfg-path', '/tmp/tmp_357bbnp']
[2024-12-04T04:40:01.215+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask sync_polygon_data
[2024-12-04T04:40:01.378+0000] {task_command.py:388} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.sync_polygon_data scheduled__2024-12-04T01:00:00+00:00 [running]> on host 1b9e534b4855
[2024-12-04T04:40:01.570+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=PolygonAPI_to_BigQuery
AIRFLOW_CTX_TASK_ID=sync_polygon_data
AIRFLOW_CTX_EXECUTION_DATE=2024-12-04T01:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-04T01:00:00+00:00
[2024-12-04T04:40:01.601+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T04:40:02.643+0000] {airbyte.py:77} INFO - Job 28 was submitted to Airbyte Server
[2024-12-04T04:40:02.644+0000] {airbyte.py:79} INFO - Waiting for job 28 to complete
[2024-12-04T04:40:05.656+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:24.160+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:30.934+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:34.118+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:37.394+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:40.951+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:44.040+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:47.231+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:50.426+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:53.595+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:56.737+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:28:59.930+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T12:29:16.483+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T13:20:21.110+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T13:20:24.224+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T13:20:27.286+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T13:20:30.322+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-04T13:20:30.352+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 80, in execute
    self.hook.wait_for_job(job_id=self.job_id, wait_seconds=self.wait_seconds, timeout=self.timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 82, in wait_for_job
    raise AirflowException(f"Job was cancelled:\n{job}")
airflow.exceptions.AirflowException: Job was cancelled:
<Response [200]>
[2024-12-04T13:20:30.355+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=PolygonAPI_to_BigQuery, task_id=sync_polygon_data, execution_date=20241204T010000, start_date=20241204T044001, end_date=20241204T132030
[2024-12-04T13:20:30.369+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task sync_polygon_data (Job was cancelled:
<Response [200]>; 2465)
[2024-12-04T13:20:30.390+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-04T13:20:30.406+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
